twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'

when@dev:
    twig:
        cache: false
        auto_reload: true

when@test:
    twig:
        strict_variables: true
